[scopes]
actions = [".github/workflows"]
auth = ["apps/auth"]
browser = ["pkgs/browser"]
config = [".github", "pkgs/config", "package.json", "turbo.json", "bunfig.toml"]
console = ["apps/console"]
deps = ["bun.lock"]
enclave = ["libs/enclave"]
indexer = ["x/indexer"]
messenger = ["x/messenger"]
oracle = ["x/oracle"]
profile = ["apps/profile"]
payment = ["apps/payment"]
react = ["pkgs/react"]
repo = [".github/Repo.toml"]
resolver = ["x/resolver"]
sdk = ["pkgs/sdk"]
search = ["apps/search"]
techdocs = ["docs"]
ui = ["pkgs/ui"]
vault = ["libs/vault"]
welcome = ["apps/welcome"]
worker = ["src", "wrangler.toml"]

[commands]
build = "devbox run build"
clean = "devbox run clean"
dev = "devbox run dev"
test = "devbox run test"
lint = "devbox run lint"
typecheck = "devbox run typecheck"
check = "devbox run check"
deploy = "devbox run deploy"
