[scopes]
actions = [".github/workflows"]
api = ["apps/api"]
config = [".github", "pkgs/config", "package.json", "turbo.json", "bunfig.toml"]
deps = ["bun.lock"]
enclave = ["libs/enclave"]
repo = [".github/Repo.toml"]
resolver = ["x/resolver"]
sdk = ["pkgs/sdk"]
techdocs = ["docs"]
ui = ["pkgs/ui"]
vault = ["libs/vault"]
web = ["apps/web"]
worker = ["x/worker"]

[commands]
build = "devbox run build"
clean = "devbox run clean"
dev = "devbox run dev"
test = "devbox run test"
lint = "devbox run lint"
typecheck = "devbox run typecheck"
check = "devbox run check"
deploy = "devbox run deploy"
